import "./globals.css";
import {Inter} from "next/font/google";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${inter.className} h-screen bg-stone-800`}>
        <main className="flex items-center justify-center p-4">
          <div className="m-auto max-w-screen-sm">
            <div className="">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
